// src/components/admin/TimetableGenerator.jsx

import React, { useState } from 'react';
import { useData } from '../../context/DataContext.jsx';
import { useTimetable } from '../../context/TimetableContext.jsx';
import { useAuth } from '../../context/AuthContext.jsx';
import { generateTimetableForDivision } from '../../utils/timetableAlgorithm.js';
import { DAYS_OF_WEEK } from '../../utils/constants.js';

const TimetableGenerator = () => {
  const { user } = useAuth();
  const { faculties, subjects, classrooms, divisions, timeSlots } = useData();
  const { saveTimetable, getTimetableByDivision, generating, setGenerating } = useTimetable();
  const [selectedDivision, setSelectedDivision] = useState('');
  const [generatedTimetable, setGeneratedTimetable] = useState(null);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    if (!selectedDivision) {
      setError('Please select a division');
      return;
    }

    setGenerating(true);
    setError('');

    try {
      // Simulate processing time
      await new Promise(resolve => setTimeout(resolve, 1000));

      const data = { faculties, subjects, classrooms, divisions, timeSlots };
      const timetable = generateTimetableForDivision(data, selectedDivision);
      
      // Set generated by current user
      timetable.generatedBy = user.id;

      setGeneratedTimetable(timetable);

      if (timetable.conflicts.length > 0) {
        setError(`Generated with ${timetable.conflicts.length} conflicts. Check the conflicts section below.`);
      }

    } catch (err) {
      setError(`Failed to generate timetable: ${err.message}`);
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = () => {
    if (generatedTimetable) {
      saveTimetable(generatedTimetable);
      alert('Timetable saved successfully!');
      setGeneratedTimetable(null);
      setSelectedDivision('');
    }
  };

  const formatTime = (timeSlotId) => {
    const slot = timeSlots.find(s => s.id === timeSlotId);
    if (!slot) return '';
    
    const formatTimeStr = (time) => {
      return new Date(`2000-01-01T${time}`).toLocaleTimeString('en-US', {
        hour: 'numeric',
        minute: '2-digit',
        hour12: true
      });
    };
    
    return `${formatTimeStr(slot.startTime)} - ${formatTimeStr(slot.endTime)}`;
  };

  const getEntryDetails = (day, timeSlotId) => {
    if (!generatedTimetable) return null;
    
    const entry = generatedTimetable.entries.find(e => 
      e.day === day && e.timeSlotId === timeSlotId
    );
    
    if (!entry) return null;

    const subject = subjects.find(s => s.id === entry.subjectId);
    const faculty = faculties.find(f => f.id === entry.facultyId);
    const classroom = classrooms.find(c => c.id === entry.classroomId);

    return { entry, subject, faculty, classroom };
  };

  const selectedDivisionData = divisions.find(d => d.id === selectedDivision);
  const existingTimetable = selectedDivision ? getTimetableByDivision(selectedDivision) : null;

  return (
    <div className="timetable-generator">
      <h2>Generate Timetable</h2>

      <div className="form-container">
        <div className="form-row">
          <div className="form-group">
            <label>Select Division:</label>
            <select
              value={selectedDivision}
              onChange={(e) => setSelectedDivision(e.target.value)}
              disabled={generating}
            >
              <option value="">Choose Division</option>
              {divisions.map(division => (
                <option key={division.id} value={division.id}>
                  {division.name} ({division.studentCount} students)
                </option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <button 
              onClick={handleGenerate}
              disabled={generating || !selectedDivision}
            >
              {generating ? 'Generating...' : 'Generate Timetable'}
            </button>
          </div>
        </div>

        {existingTimetable && (
          <div style={{padding: '1rem', background: '#fff3cd', borderRadius: '4px', marginTop: '1rem'}}>
            <strong>Note:</strong> A timetable already exists for this division. 
            Generating a new one will replace the existing timetable when saved.
          </div>
        )}

        {error && (
          <div className="error-message" style={{marginTop: '1rem'}}>
            {error}
          </div>
        )}
      </div>

      {generatedTimetable && (
        <div className="generated-timetable">
          <div className="timetable-header">
            <h3>Generated Timetable for {selectedDivisionData?.name}</h3>
            <div>
              <button onClick={handleSave} className="btn-save">
                Save Timetable
              </button>
              <button 
                onClick={() => setGeneratedTimetable(null)}
                style={{marginLeft: '1rem', background: '#6c757d'}}
              >
                Discard
              </button>
            </div>
          </div>

          {/* Timetable Grid */}
          <div className="timetable-grid">
            <table className="timetable-table">
              <thead>
                <tr>
                  <th>Time</th>
                  {DAYS_OF_WEEK.map(day => (
                    <th key={day}>{day}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {timeSlots.filter(slot => !slot.isLunch).map(slot => (
                  <tr key={slot.id}>
                    <td className="time-cell">
                      {formatTime(slot.id)}
                    </td>
                    {DAYS_OF_WEEK.map(day => {
                      const details = getEntryDetails(day, slot.id);
                      return (
                        <td key={day} className="lecture-cell">
                          {details ? (
                            <div className="lecture-info">
                              <div className="subject-name">
                                {details.subject?.name}
                              </div>
                              <div className="faculty-name">
                                {details.faculty?.name}
                              </div>
                              <div className="classroom-name">
                                {details.classroom?.name}
                              </div>
                            </div>
                          ) : (
                            <div className="empty-slot">-</div>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Conflicts */}
          {generatedTimetable.conflicts.length > 0 && (
            <div className="conflicts-section">
              <h4>Conflicts ({generatedTimetable.conflicts.length})</h4>
              <ul>
                {generatedTimetable.conflicts.map((conflict, index) => (
                  <li key={index} style={{color: '#e74c3c'}}>
                    {conflict}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Statistics */}
          <div className="timetable-stats">
            <h4>Statistics</h4>
            <div className="stats-row">
              <span>Total Lectures Scheduled: {generatedTimetable.entries.length}</span>
              <span>Conflicts: {generatedTimetable.conflicts.length}</span>
              <span>Success Rate: {Math.round((generatedTimetable.entries.length / (generatedTimetable.entries.length + generatedTimetable.conflicts.length)) * 100)}%</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TimetableGenerator;